# syntax=docker/dockerfile:1

ARG NODE_VERSION=22.1.0

FROM node:${NODE_VERSION}-alpine as build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

FROM nginx:alpine as final

COPY --from=build /usr/src/app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf