services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - GH_CLIENT_ID=${GH_CLIENT_ID}
      - GH_SECRET=${GH_SECRET}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:80

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
