version: "3"
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}
      GH_CLIENT_ID: ${GH_CLIENT_ID}
      GH_SECRET: ${GH_SECRET}
      JWT_SECRET: ${JWT_SECRET}
