version: "3"
services:
website:
  build:
    context: ./website
    dockerfile: Dockerfile
  volumes:
    - website:/website/client/build/ # build files will be added at this directory !!!

nginx:
  build:
    context: ./nginx
    dockerfile: Dockerfile
  ports:
    - "80:80"
  volumes:
    - website:/usr/share/nginx/html/website # Copy React App's build files to the Nginx directory

volumes:
  website:
