services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - net

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: jpswann0208/my-backend${IMAGE_TAG}
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - GH_CLIENT_ID=${GH_CLIENT_ID}
      - GH_SECRET=${GH_SECRET}
    expose:
      - 8000
    depends_on:
      - mongo
    restart: always
    networks:
      - net

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    image: jpswann0208/my-frontend${IMAGE_TAG}
    expose:
      - 3000
    depends_on:
      - backend
    restart: always
    networks:
      - net

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - mongo-data:/data/db
    networks:
      - net

volumes:
  mongo-data:
networks:
  net:
    external: true
