name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull jpswann0208/jpswann-app:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f jpswann-app-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 jpswann0208/jpswann-app
