name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull jpswann0208/jpswann-app:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f jpswann-app-container || true
      - name: Run Docker Container
        run: sudo docker run -d -t -i -e MONGO_URI=${{ secrets.MONGO_URI }} -e GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} -e GH_SECRET=${{ secrets.GH_SECRET }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -p 8080:8080 --name jpswann-app-container jpswann0208/jpswann-app
      - name: Clean up unused Docker images
        run: sudo docker image prune -f
