name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull jpswann0208/jpswann-app:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f jpswann-app-container || true

      - name: Run Docker Container
        run: sudo docker-compose up -d
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_SECRET: ${{ secrets.GH_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Clean up unused Docker images
        run: sudo docker image prune -f
