name: CI Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          version: "latest"

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Run Tests
        run: |
          docker-compose up -d
          # Add commands to run your tests here, for example:
          docker-compose run --rm my-service npm test
          # Shut down services after tests
          docker-compose down

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push Docker Images
        run: |
          docker-compose push
