name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t jpswann0208/jpswann-app .

      - name: Publish Docker Image
        run: docker push jpswann0208/jpswann-app:latest

      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose up -d
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_SECRET: ${{ secrets.GH_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Clean up unused Docker images
        run: docker image prune -f
